create extension if not exists pgcrypto;

create table if not exists public.mystic_reports (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  input jsonb not null,
  profile jsonb not null,
  report text not null,
  mode text not null check (mode in ('ai', 'demo')),
  status_message text not null,
  created_at timestamptz not null default now()
);

alter table public.mystic_reports enable row level security;

create index if not exists mystic_reports_created_at_idx
  on public.mystic_reports (created_at desc);

comment on table public.mystic_reports is
  'AI mystic reports generated by the MVP website. Accessed only through Next.js server routes using the service role key.';

create table if not exists public.manual_orders (
  order_id text primary key,
  report_id text not null,
  product_type text not null check (product_type in ('full_report', 'followup_room')),
  product_name text not null,
  amount text not null,
  status text not null default 'pending' check (status in ('pending', 'paid', 'unlocked', 'exception')),
  customer_name text not null default '',
  wechat text not null default '',
  report_link text not null default '',
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.manual_orders enable row level security;

create index if not exists manual_orders_created_at_idx
  on public.manual_orders (created_at desc);

create index if not exists manual_orders_report_id_idx
  on public.manual_orders (report_id);

comment on table public.manual_orders is
  'Manual payment orders for the MVP. Accessed only through Next.js server routes using the service role key.';
