create extension if not exists pgcrypto;

create table if not exists public.mystic_reports (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  input jsonb not null,
  profile jsonb not null,
  report text not null,
  mode text not null check (mode in ('ai', 'demo')),
  status_message text not null,
  created_at timestamptz not null default now()
);

alter table public.mystic_reports enable row level security;

create index if not exists mystic_reports_created_at_idx
  on public.mystic_reports (created_at desc);

comment on table public.mystic_reports is
  'AI mystic reports generated by the MVP website. Accessed only through Next.js server routes using the service role key.';
